<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGZybNLz\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGZybNLz/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGZybNLz.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGZybNLz\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGZybNLz\App_KernelDevDebugContainer([
    'container.build_hash' => 'GZybNLz',
    'container.build_id' => '13437309',
    'container.build_time' => 1708679954,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGZybNLz');
