version: "3"

services:
    php:
        container_name: php
        image: php:8.2-fpm-alpine
        build:
            context: ./docker/php
        volumes:
            - ./:/var/www/
        networks:
            - symfony_app

    nginx:
        container_name: nginx
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./:/var/www/
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - symfony_app
    db:
        container_name: database
        image: postgres
        volumes:
            - ./data:/var/lib/postgres
        environment:
            POSTGRES_DB: ${PG_DATABASE}
            POSTGRES_USER: ${PG_USER}
            POSTGRES_PASSWORD: ${PG_PASSWORD}
        ports:
            - "5432:5432"
        networks:
            - symfony_app

volumes:
    db_app:

networks:
    symfony_app:
